# Generated by Django 3.2.9 on 2021-12-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imagen',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
