# Generated by Django 3.2.9 on 2021-12-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imagen',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
